//! Compile the versioned `data/*.json` registries into the crate (source-only;
//! no runtime file access — the air-gapped target carries its world view in the
//! binary). Each source is validated against the structural invariants its
//! `data/schemas/*.schema.json` documents; a violation is a `panic!` here, which
//! FAILS THE BUILD (fail-closed: a malformed registry never ships).
//!
//! std-only: a small hand-rolled JSON reader (below) parses the data files —
//! this code is never linked into the rlib, so it carries no dependency cost.

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let dest = Path::new(&out_dir).join("registries.rs");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from data/*.json — do not edit.\n");

    emit_nations(&mut out);

    fs::write(&dest, out).expect("write registries.rs");

    // Rebuild whenever a data source or its schema changes.
    println!("cargo:rerun-if-changed=data");
    println!("cargo:rerun-if-changed=build.rs");
}

// ---------------------------------------------------------------------------
// data/iso-3166-1-alpha-3.json  →  pub static ISO3166: &[&str]
// schema: { version:string, source:string, codes:array<string, each 3 uppercase ASCII> }
// ---------------------------------------------------------------------------
fn emit_nations(out: &mut String) {
    let text = read_data("iso-3166-1-alpha-3.json");
    let json = Json::parse(&text).unwrap_or_else(|e| panic!("iso-3166-1-alpha-3.json: {e}"));

    require_str(&json, "version", "iso-3166-1-alpha-3.json");
    require_str(&json, "source", "iso-3166-1-alpha-3.json");
    let codes = json
        .get("codes")
        .and_then(Json::as_arr)
        .unwrap_or_else(|| panic!("iso-3166-1-alpha-3.json: 'codes' must be an array"));
    if codes.is_empty() {
        panic!("iso-3166-1-alpha-3.json: 'codes' must be non-empty");
    }

    // Validate + dedupe + sort (binary_search on the emitted table requires sorted).
    let mut set: BTreeSet<String> = BTreeSet::new();
    for c in codes {
        let code = c
            .as_str()
            .unwrap_or_else(|| panic!("iso-3166-1-alpha-3.json: every code must be a string"));
        if !is_three_upper_ascii(code) {
            panic!("iso-3166-1-alpha-3.json: code not 3 uppercase ASCII: {code:?}");
        }
        if !set.insert(code.to_string()) {
            panic!("iso-3166-1-alpha-3.json: duplicate code: {code:?}");
        }
    }

    out.push_str("pub static ISO3166: &[&str] = &[");
    for code in &set {
        out.push('"');
        out.push_str(code);
        out.push_str("\",");
    }
    out.push_str("];\n");
}

fn is_three_upper_ascii(s: &str) -> bool {
    s.len() == 3 && s.bytes().all(|b| b.is_ascii_uppercase())
}

fn read_data(name: &str) -> String {
    let dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let path = Path::new(&dir).join("data").join(name);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

fn require_str(json: &Json, key: &str, src: &str) {
    match json.get(key).and_then(Json::as_str) {
        Some(v) if !v.is_empty() => {}
        _ => panic!("{src}: '{key}' must be a non-empty string"),
    }
}

// ---------------------------------------------------------------------------
// Minimal std-only JSON reader (build-time only; not shipped).
// Handles objects, arrays, strings (with basic escapes), numbers, bools, null.
// ---------------------------------------------------------------------------
// A complete JSON reader must represent every value kind to parse valid input,
// even the kinds the current emitters don't inspect (bool/number appear in the
// CUI registry's `sanctions`/count fields but #26 only reads its string keys).
#[allow(dead_code)]
#[derive(Debug, Clone)]
enum Json {
    Null,
    Bool(bool),
    Num(f64),
    Str(String),
    Arr(Vec<Json>),
    Obj(Vec<(String, Json)>),
}

impl Json {
    fn parse(s: &str) -> Result<Json, String> {
        let bytes: Vec<char> = s.chars().collect();
        let mut p = Parser {
            chars: &bytes,
            pos: 0,
        };
        p.skip_ws();
        let v = p.value()?;
        p.skip_ws();
        if p.pos != p.chars.len() {
            return Err(format!("trailing input at char {}", p.pos));
        }
        Ok(v)
    }

    fn get(&self, key: &str) -> Option<&Json> {
        match self {
            Json::Obj(kvs) => kvs.iter().find(|(k, _)| k == key).map(|(_, v)| v),
            _ => None,
        }
    }

    fn as_str(&self) -> Option<&str> {
        match self {
            Json::Str(s) => Some(s.as_str()),
            _ => None,
        }
    }

    fn as_arr(&self) -> Option<&[Json]> {
        match self {
            Json::Arr(a) => Some(a.as_slice()),
            _ => None,
        }
    }
}

struct Parser<'a> {
    chars: &'a [char],
    pos: usize,
}

impl Parser<'_> {
    fn peek(&self) -> Option<char> {
        self.chars.get(self.pos).copied()
    }

    fn bump(&mut self) -> Option<char> {
        let c = self.peek();
        if c.is_some() {
            self.pos += 1;
        }
        c
    }

    fn skip_ws(&mut self) {
        while matches!(self.peek(), Some(' ' | '\t' | '\n' | '\r')) {
            self.pos += 1;
        }
    }

    fn value(&mut self) -> Result<Json, String> {
        self.skip_ws();
        match self.peek() {
            Some('{') => self.object(),
            Some('[') => self.array(),
            Some('"') => Ok(Json::Str(self.string()?)),
            Some('t') | Some('f') => self.boolean(),
            Some('n') => self.null(),
            Some(c) if c == '-' || c.is_ascii_digit() => self.number(),
            other => Err(format!("unexpected {other:?} at char {}", self.pos)),
        }
    }

    fn object(&mut self) -> Result<Json, String> {
        self.expect('{')?;
        let mut kvs = Vec::new();
        self.skip_ws();
        if self.peek() == Some('}') {
            self.bump();
            return Ok(Json::Obj(kvs));
        }
        loop {
            self.skip_ws();
            let key = self.string()?;
            self.skip_ws();
            self.expect(':')?;
            let val = self.value()?;
            kvs.push((key, val));
            self.skip_ws();
            match self.bump() {
                Some(',') => continue,
                Some('}') => break,
                other => return Err(format!("expected ',' or '}}', got {other:?}")),
            }
        }
        Ok(Json::Obj(kvs))
    }

    fn array(&mut self) -> Result<Json, String> {
        self.expect('[')?;
        let mut items = Vec::new();
        self.skip_ws();
        if self.peek() == Some(']') {
            self.bump();
            return Ok(Json::Arr(items));
        }
        loop {
            let val = self.value()?;
            items.push(val);
            self.skip_ws();
            match self.bump() {
                Some(',') => continue,
                Some(']') => break,
                other => return Err(format!("expected ',' or ']', got {other:?}")),
            }
        }
        Ok(Json::Arr(items))
    }

    fn string(&mut self) -> Result<String, String> {
        self.expect('"')?;
        let mut s = String::new();
        loop {
            match self.bump() {
                Some('"') => return Ok(s),
                Some('\\') => match self.bump() {
                    Some('"') => s.push('"'),
                    Some('\\') => s.push('\\'),
                    Some('/') => s.push('/'),
                    Some('n') => s.push('\n'),
                    Some('t') => s.push('\t'),
                    Some('r') => s.push('\r'),
                    Some('b') => s.push('\u{0008}'),
                    Some('f') => s.push('\u{000C}'),
                    Some('u') => {
                        let mut code = 0u32;
                        for _ in 0..4 {
                            let d = self
                                .bump()
                                .and_then(|c| c.to_digit(16))
                                .ok_or("bad \\u escape")?;
                            code = code * 16 + d;
                        }
                        s.push(char::from_u32(code).ok_or("bad \\u codepoint")?);
                    }
                    other => return Err(format!("bad escape {other:?}")),
                },
                Some(c) => s.push(c),
                None => return Err("unterminated string".into()),
            }
        }
    }

    fn boolean(&mut self) -> Result<Json, String> {
        if self.consume("true") {
            Ok(Json::Bool(true))
        } else if self.consume("false") {
            Ok(Json::Bool(false))
        } else {
            Err(format!("bad literal at char {}", self.pos))
        }
    }

    fn null(&mut self) -> Result<Json, String> {
        if self.consume("null") {
            Ok(Json::Null)
        } else {
            Err(format!("bad literal at char {}", self.pos))
        }
    }

    fn number(&mut self) -> Result<Json, String> {
        let start = self.pos;
        while matches!(self.peek(), Some(c) if c == '-' || c == '+' || c == '.' || c == 'e' || c == 'E' || c.is_ascii_digit())
        {
            self.pos += 1;
        }
        let text: String = self.chars[start..self.pos].iter().collect();
        text.parse::<f64>()
            .map(Json::Num)
            .map_err(|_| format!("bad number {text:?}"))
    }

    fn expect(&mut self, c: char) -> Result<(), String> {
        match self.bump() {
            Some(got) if got == c => Ok(()),
            other => Err(format!("expected {c:?}, got {other:?}")),
        }
    }

    fn consume(&mut self, lit: &str) -> bool {
        let end = self.pos + lit.chars().count();
        if end <= self.chars.len() && self.chars[self.pos..end].iter().collect::<String>() == lit {
            self.pos = end;
            true
        } else {
            false
        }
    }
}
